version: "2.3"

services:
    fastapi:
        container_name: fastapi
        build: fastapi
        hostname: fastapi
        restart: always
        oom_kill_disable: true
        privileged: true
        tty: true
        environment:
            - API_PORT=9000
        expose:
            - "9000"

        volumes:
            - ./fastapi:/py/
        working_dir: /py
        networks:
            - back-tier


    flask:
        container_name: flask
        build: flask
        hostname: flask
        restart: always
        oom_kill_disable: true
        privileged: true
        tty: true
        environment:
            - API_PORT=9000
        expose:
            - "9000"

        volumes:
            - ./flask:/py/
        working_dir: /py
        networks:
            - back-tier

    robyn:
        container_name: robyn
        build: robyn
        hostname: robyn
        restart: always
        oom_kill_disable: true
        privileged: true
        tty: true
        environment:
            - API_PORT=9000
        expose:
            - "9000"

        volumes:
            - ./robyn:/py/
        working_dir: /py
        networks:
            - back-tier

    client:
        container_name: client
        build: client
        hostname: client
        restart: always
        oom_kill_disable: true
        privileged: true
        tty: true
        depends_on:
            - fastapi
            - flask
            - robyn
        volumes:
            - ./client:/py/
        working_dir: /py
        networks:
            - back-tier

networks:
    back-tier:
        driver: bridge
