[package]
name = "restapi"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
zune-jpeg = "0.4.0"
tower-http = { version = "0.4.4", features = ["cors"] }
