FROM rust:1.85.1 AS build-env
WORKDIR /app
COPY . /app

# ENV TARGET=<arch-OS>-musl
# aarch64-unknown-linux-musl, x86_64-unknown-linux-musl, etc.
RUN rustup target list | grep installed | head -n 1 | sed 's/-[^-]*$/-musl/; s/ (installed)//' > /targets
RUN rustup target add $(cat /targets)
RUN cargo build --release --locked --target $(cat /targets) && \
    mv /app/target/$(cat /targets)/release/restapi /app/restapi

FROM scratch AS runtime
COPY --from=build-env /app/restapi /server
EXPOSE 8080
CMD ["/server"]

# Development
# docker run --name rapi --rm -it --net simple_api_template_back-tier -v $PWD:/app -w /app -e API_PORT=9000 -p 9000 rust:1.85.1 bash