FROM rust:1.85.1 AS build-env
WORKDIR /app
COPY . /app

# ENV TARGET=<arch-OS>-musl
# aarch64-unknown-linux-musl, x86_64-unknown-linux-musl, etc.
RUN rustup target list | grep installed | head -n 1 | sed 's/-[^-]*$/-musl/; s/ (installed)//' > /targets
RUN rustup target add $(cat /targets)
RUN cargo build --release --locked --target $(cat /targets)

FROM scratch AS runtime
COPY --from=build-env /app/target/aarch64-unknown-linux-musl/release/restapi /server
EXPOSE 8080
CMD ["/server"]
